version: '3.7'

services:
  web:
    image: cruelgangsta/py_feedback_app
    ports:
      - "8080:5000"
    environment:
      SQL_HOST: db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: feedback
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
